# Site settings
title: 张亚琪の博客
email: zhangyingyun001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 本博客利用了BootStrap。后续会记录我的 BootStrap 学习。

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yingyun001.github.io/" # the base hostname & protocol for your site
twitter_username: yingyun001
github_username:  yingyun001

# Build settings
markdown: kramdown
